FROM nginx:1.25-alpine

# 1. Удаляем стандартные файлы Nginx, чтобы они не мешались
RUN rm -rf /usr/share/nginx/html/*

# 2. Копируем только твой сайт в папку, которую Nginx раздает по умолчанию
COPY index.html /usr/share/nginx/html/index.html
# Если у тебя есть папки css/js, добавь: COPY assets/ /usr/share/nginx/html/assets/

# 3. Копируем твой конфиг (прокси-сервер) на место стандартного
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80